### ISSUE TITLE
How to select multiple dates

### ISSUE THREAD

**Issue by rameshvoltella** [gongmingqm10/awesome-calendar#1]
hi, this is not a isuue, can you tell how to selct multiple dates, its like if i want to make 3 different days in this calender example 3,7,8 date of a month, how can we achive this

**Comment by gongmingqm10** [comment]
Hi, there is no support for what you said multiple dates selection. But it's easy to extend if the multiple dates selection is really what you want. Find [CalenderCell#updateSelection](https://github.com/gongmingqm10/awesome-calendar/blob/master/app/src/main/java/net/gongmingqm10/calendar/view/CalendarCell.java) method. It contains all the updates for the UI. Generally this method is called in Adapter.
